# This is a basic workflow to help you get started with Actions
name: My pipeline
on: workflow_call
jobs: 
  my_job:
    runs-on: ubuntu-latest
    steps:
     - run: echo Hello World!
            echo Welcome to Github Actions!

